#!/usr/bin/env bash
# ---- PLATFORM-SPECIFIC SEAM ----
# The only GitHub-specific call in this script: `gh issue create`. On
# GitLab, swap for `glab issue create`. Everything upstream (the
# post-mortem content itself, generated by generate_postmortem.py) is
# unaffected by this swap.
#
# Usage: open_incident_issue.sh <title> <body_file> <labels>
# Requires: gh CLI authenticated (GH_TOKEN env var)
set -euo pipefail

TITLE="${1:?}"
BODY_FILE="${2:?}"
LABELS="${3:-incident,needs-triage}"

gh issue create --title "$TITLE" --body-file "$BODY_FILE" --label "$LABELS"
# ---- END SEAM ----
